### ISSUE TITLE
Meta Config Does Not Work

### ISSUE THREAD

**Issue by Graftax** [CubeCoders/AMPTemplates#104] opened 2022-03-23 22:19 UTC
Using AMP Release "Triton" v2.3.2.4, built 22/02/2022 10:57.

In dont-starve-together.kvp there are these lines.

`Meta.ConfigManifest=dont-starve-togetherconfig.json`
`Meta.MetaConfigManifest=dont-starve-togethermetaconfig.json`

They do not appear to work. I put the files referenced here in ~/.ampdata/instances/DontStarveTogether and restarted the instance. When I checked the config the options I expected were not there.

I renamed them to "configmanifest" and "metaconfig.json" and restarted the instance and the configuration options showed up in the GUI as I expected.

The fact that the lines mentioned above did not work is the problem and resulted in hours of me searching for the correct configuration and file location.

At minimum I would expect a warning in the UI about trying to load a config that doesn't exist.

**Comment by IceOfWraith** [comment] 2022-03-23 22:38
The lines you're referencing are for a new instance getting created. AMP is functioning as intended, but it sounds like you were trying to put the files into an existing instance rather than putting them into ADS and creating a new one and letting it handle the process. Here are the steps for future issues if someone comes across this same trouble.

1. Download the file from GitHub by going to the pull request or AMPTemplates repo, click each file, right click the "raw" button, and Save As.
2. Place the kvp and json files in your AMP datastore under `(ADS Instance Name)/Plugins/ADSModule/GenericTemplates`
3. Restart ADS.
4. The game server can be selected like any other when creating a new instance.
5. Some games require special config files be included if the pull request hasn't been merged. You'll need to contact the creator of the config to determine where to place them.

**Closed by IceOfWraith** 2022-03-23 22:38 UTC

**Comment by Graftax** [comment] 2022-03-24 15:52
Yeah, there should be a "How to use templates" section in the readme, because I did not find this info after hours of searching. What you described sounds so much easier, I just wish that there was documentation anywhere that had told me to do it that way.

**Comment by IceOfWraith** [comment] 2022-03-24 15:58
Mike plans to include a button in AMP soon that will grab the items from GitHub automatically so if a new config is released they can be downloaded outside of an AMP release. :)

**Comment by Shinynecrid** [comment] 2022-03-24 16:01
the expected behavior is to place the .kvp and .json files in your ADS instance under the /Plugins/ADSModule/GenericTemplates directory along side the other .kvp and .json files. Then restart ADS, and your new configuration will appear as an option when you select 'Create Instance'. This is until a updated system in place.

**Comment by Graftax** [comment] 2022-03-24 16:02
Is there like, documentation somewhere I can look at? I just feel like an idiot for not knowing. If multiple people know how this works there must be some source of information, right? I want that.

**Comment by Shinynecrid** [comment] 2022-03-24 16:06
https://github.com/CubeCoders/AMP/wiki/Configuring-the-'Generic'-AMP-module is anything relating to Generic Module.

**Comment by IceOfWraith** [comment] 2022-03-24 16:09
The message I supplied is from the Discord as well. It's one of the pinned messages if you have that.

**Comment by Shinynecrid** [comment] 2022-03-24 16:13
> The message I supplied is from the Discord as well. It's one of the pinned messages if you have that.

I forgot you pinned that haha
