### ISSUE TITLE
Icarus Dedicated Server Add Request

### ISSUE THREAD

**Issue by Alybee117** [CubeCoders/AMPTemplates#232] opened 2022-11-19 19:32 UTC
Hello was directed to this form, from the discord server. 

Now that Icarus has released a Dedicated server branch would it be possible to add this too the list?
thank you very much.

https://github.com/RocketWerkz/IcarusDedicatedServer/wiki/Server-Setup

**Comment by Greelan** [comment] 2022-11-19 21:25
I can add this in the next day or so. In the meantime can you provide log lines from the dedicated server that show when a user joins the server and then leaves?

**Comment by Alybee117** [comment] 2022-11-19 22:54
Im actually struggling to get the server to run myself.

**Comment by Greelan** [comment] 2022-11-19 23:05
Ah, lol, well when I have the template prepared you can test it on that. I don't intend buying the game myself

**Comment by Greelan** [comment] 2022-11-20 10:32
I've got the template working, at least to create and launch a prospect. Loading existing saves however is an issue - the server throws an error. I've asked on the Icarus discord about it

Any chance you can find the file `prospectlist.json` that apparently is installed with the client and gives a list of all the prospect types? I want to add them to the UI for easy creation of prospects

**Comment by Greelan** [comment] 2022-11-21 00:14
OK, working template is in `Greelan/AMPTemplates:dev`.

I've clarified that the issue with loading existing saves was because of data corruption caused by the server being shutdown by AMP without a clean exit. Unfortunately the only method that works reliably in AMP to shutdown the server does not trigger a clean shutdown. The issue can be avoided by the server returning to the lobby first - the return to lobby triggers a proper save, and therefore AMP's subsequent untidy exit does not cause data issues.

@Alybee117 test it out and let me know feedback. Also, as mentioned, getting a copy of `prospectlist.json` would be very helpful, as then I can populate the list in the UI rather than have people guessing what prospect types are valid, given the format required is very specific.

**Comment by gkuba** [comment] 2022-11-21 06:12
Re-installing Icarus now I'll get you the file and can help with testing

**Comment by gkuba** [comment] 2022-11-21 06:48
I do not see that file in the game dir or in the %localappdata%/Icarus dir. I'll keep poking around though.

**Comment by Greelan** [comment] 2022-11-21 07:00
Hmm. I've asked on their discord for the location. Someone mentioned it literally 2 days ago when another person asked about the prospect types

**Comment by Greelan** [comment] 2022-11-21 07:16
Somewhat unhelpfully, I've been told the answer to get the list is "datamining", to discover the internal names for the prospect types... Not a very practical setup for the dedicated server

**Comment by gkuba** [comment] 2022-11-21 07:18
Ok I found more info. For this to work they will also have to opt into and run the Dedilive branch on the client side.
- Branch: Dedilive
- PW: 'IWillBackUpMyLocalSave'

We will want to put a note with this info as well until its fully live. 

Pulling down your configs now to see if its in the dedicated server dirs. If its not there I may see if I can unpack the game files to get that list. Also if its easier you can msg me in discord I allowed the server.

**Comment by Greelan** [comment] 2022-11-21 07:21
So it seems the long way around is to run the server, connect with a client to the lobby, select a prospect in the lobby UI to create it, then check in the ServerSettings.ini for the last prospect created. Then do this again for each option....

**Comment by gkuba** [comment] 2022-11-21 07:23
hehe figured. I may just look up my god old unpack unreal tools again and see if its in there first.

**Comment by Greelan** [comment] 2022-11-21 07:39
I like your thinking. If we can get internal name and display name, we are golden

**Comment by gkuba** [comment] 2022-11-21 07:53
Tada!! 
![image](https://user-images.githubusercontent.com/1753639/202994564-008e5b4c-7f10-421e-8ff0-0c62a4d81640.png)

Getting you a cleaned up list of just the names now.

**Comment by gkuba** [comment] 2022-11-21 08:01
[prospectlist.txt](https://github.com/CubeCoders/AMPTemplates/files/10054522/prospectlist.txt)

This should be all of them.

**Comment by gkuba** [comment] 2022-11-21 08:05
Looks like they did the same thing I did over on the Icarus discord. Let me get you a better one with mission name tied to internal name.

**Comment by Greelan** [comment] 2022-11-21 08:43
So that was easy! My repo now updated :)

Thanks for the input!

**Comment by Greelan** [comment] 2022-11-21 08:44
I've just ordered it though alphabetically. That seemed the best but let me know if you think otherwise

**Comment by gkuba** [comment] 2022-11-21 08:46
Alpha works. I just did this to break them into their categories to make searching a little easier.

**Comment by Greelan** [comment] 2022-11-21 08:47
Maybe better like Outposts:Styx, Outposts:Arcwood etc?

**Comment by gkuba** [comment] 2022-11-21 08:48
Yeah as they will be looking for the in game name tbh.

**Comment by gkuba** [comment] 2022-11-21 08:49
Np, when you are done I'll re-pull the repo and give it a test.

**Comment by Greelan** [comment] 2022-11-21 09:27
OK, that's now done.

Only question on the prospect types is whether I should allow for a custom setting, eg if mods are allowed/contemplated - so someone could include the internal name of their own prospect?

Also, user join and leave log lines from AMP would be great if possible. Thanks.

**Comment by gkuba** [comment] 2022-11-21 09:29
I'll see what I can get ya 

I doubt Mods will be officially supported just like with DayZ.

**Comment by gkuba** [comment] 2022-11-21 10:06
So when it starts up even with  a prospect selected it seems to go to the lobby which is fine. There we can load / create a new prospect. So that list may not even be needed at all. 

```
[2022.11.21-10.01.11:587][601]LogIcarusSession: Icarus Session Node Exit - Success
[2022.11.21-10.01.11:587][601]LogIcarusGameModeSurvival: Display: OnUpdateUnrealSessionSuccess
[2022.11.21-10.01.11:587][601]LogOnlineProspect: RPC: GetProspect response - Succeeded
03:01:27
[2022.11.21-10.01.27:086][ 69]LogIcarusPlayerController: Display: ServerLeaveProspectSession - LeaveProspectSessionType: ReturnToCharacterSelect
[2022.11.21-10.01.27:086][ 69]LogIcarusPlayerController: Display: ServerFinaliseLeaveProspectSession - ServerPendingLeaveProspectSession: ReturnToCharacterSelect | LeaveProspectSessionType: ReturnToCharacterSelect
[2022.11.21-10.01.27:086][ 69]LogIcarusPlayerController: Display: OnRep_ReplicatedLeftProspectSession - ReplicatedLeftProspectSession: ReturnToCharacterSelect
[2022.11.21-10.01.27:316][ 76]LogNet: UChannel::ReceivedSequencedBunch: Bunch.bClose == true. ChIndex == 0. Calling ConditionalCleanUp.
[2022.11.21-10.01.27:316][ 76]LogNet: UChannel::CleanUp: ChIndex == 0. Closing connection. [UChannel] ChIndex: 0, Closing: 0 [UNetConnection] RemoteAddr: 76561198051191700:19132, Name: SteamNetConnection_2147479445, Driver: GameNetDriver SteamNetDriver_2147481826, IsServer: YES, PC: BP_IcarusPlayerControllerSurvival_C_2147479438, Owner: BP_IcarusPlayerControllerSurvival_C_2147479438, UniqueId: Steam:UNKNOWN [0x1100001056B6B94]
[2022.11.21-10.01.27:316][ 76]LogNet: UNetConnection::Close: [UNetConnection] RemoteAddr: 76561198051191700:19132, Name: SteamNetConnection_2147479445, Driver: GameNetDriver SteamNetDriver_2147481826, IsServer: YES, PC: BP_IcarusPlayerControllerSurvival_C_2147479438, Owner: BP_IcarusPlayerControllerSurvival_C_2147479438, UniqueId: Steam:UNKNOWN [0x1100001056B6B94], Channels: 57, Time: 2022.11.21-10.01.27
[2022.11.21-10.01.27:316][ 76]LogNet: UChannel::Close: Sending CloseBunch. ChIndex == 0. Name: [UChannel] ChIndex: 0, Closing: 0 [UNetConnection] RemoteAddr: 76561198051191700:19132, Name: SteamNetConnection_2147479445, Driver: GameNetDriver SteamNetDriver_2147481826, IsServer: YES, PC: BP_IcarusPlayerControllerSurvival_C_2147479438, Owner: BP_IcarusPlayerControllerSurvival_C_2147479438, UniqueId: Steam:UNKNOWN [0x1100001056B6B94]
[2022.11.21-10.01.27:348][ 77]LogConnectedPlayers: Display: RemoveConnectedPlayer - UserId: 76561198051191700
[2022.11.21-10.01.27:348][ 77]LogConnectedPlayers: Verbose: OnRep_ConnectedPlayers
[2022.11.21-10.01.27:353][ 77]LogIcarusGameModeSurvival: -------- Server is now empty --------
[2022.11.21-10.01.27:353][ 77]LogOnline: STEAM: Removing P2P Session Id: UNKNOWN [0x1100001056B6B94], Channel: 19132, IdleTime: 0.038
03:01:28
[2022.11.21-10.01.28:864][124]LogOnline: STEAM: Closing channel 19132 with user 76561198051191700
[2022.11.21-10.01.28:867][124]LogOnline: STEAM: 76561198051191700 has been removed.
03:02:50
[2022.11.21-10.02.50:787][622]LogOnline: STEAM: Adding P2P connection information with user 76561198051191700 (Name: UNKNOWN [0x1100001056B6B94])
03:02:54
[2022.11.21-10.02.54:343][729]LogNet: NotifyAcceptingConnection accepted from: 76561198051191700:19132
[2022.11.21-10.02.54:343][729]LogNet: NotifyAcceptingConnection accepted from: 76561198051191700:19132
[2022.11.21-10.02.54:344][729]LogNet: NotifyAcceptingConnection accepted from: 76561198051191700:19132
[2022.11.21-10.02.54:344][729]LogNet: NotifyAcceptingConnection accepted from: 76561198051191700:19132
[2022.11.21-10.02.54:376][730]LogNet: NotifyAcceptingConnection accepted from: 76561198051191700:19132
[2022.11.21-10.02.54:376][730]LogNet: Server accepting post-challenge connection from: 76561198051191700:19132
[2022.11.21-10.02.54:377][730]PacketHandlerLog: Loaded PacketHandler component: OnlineSubsystemSteam.SteamAuthComponentModuleInterface ()
[2022.11.21-10.02.54:377][730]PacketHandlerLog: Loaded PacketHandler component: Engine.EngineHandlerComponentFactory (StatelessConnectHandlerComponent)
[2022.11.21-10.02.54:377][730]LogOnline: STEAM: Adding user 76561198051191700:19132 from RegisterConnection
[2022.11.21-10.02.54:377][730]LogNet: NotifyAcceptedConnection: Name: Terrain_016, TimeStamp: 11/21/22 02:02:54, [UNetConnection] RemoteAddr: 76561198051191700:19132, Name: SteamNetConnection_2147477781, Driver: GameNetDriver SteamNetDriver_2147481826, IsServer: YES, PC: NULL, Owner: NULL, UniqueId: INVALID
[2022.11.21-10.02.54:377][730]LogNet: AddClientConnection: Added client connection: [UNetConnection] RemoteAddr: 76561198051191700:19132, Name: SteamNetConnection_2147477781, Driver: GameNetDriver SteamNetDriver_2147481826, IsServer: YES, PC: NULL, Owner: NULL, UniqueId: INVALID
[2022.11.21-10.02.54:478][731]LogOnline: STEAM: AUTH HANDLER: Sending auth result to user 76561198051191700 with flag success? 1
[2022.11.21-10.02.54:511][732]LogNet: NotifyAcceptingChannel Control 0 server World /Game/Maps/Terrain_016_OLY/Terrain_016.Terrain_016: Accepted
[2022.11.21-10.02.54:511][732]LogNet: Remote platform little endian=1
[2022.11.21-10.02.54:511][732]LogNet: This platform little endian=1
[2022.11.21-10.02.54:545][733]LogNet: Login request: ?password=1234?Name=Katala Swiftwind userId: Steam:UNKNOWN [0x1100001056B6B94] platform: Steam
03:02:58
[2022.11.21-10.02.58:374][849]LogNet: Client netspeed is 640000
[2022.11.21-10.02.58:374][849]LogNet: Join request: /Game/Maps/DedicatedServerEntry?password=1234?Name=Katala Swiftwind?SplitscreenCount=1
[2022.11.21-10.02.58:384][849]AnimBlueprintLog: Warning: SLOTNODE: 'ActionMontage' in animation instance class CHA_3RD_MAL_01_AnimBP_C already exists. Remove duplicates from the animation graph for this class.
[2022.11.21-10.02.58:396][849]LogActor: Warning: DDGIVolume /Game/Maps/Terrain_016_OLY/Terrain_016.Terrain_016:PersistentLevel.DDGIVolume_2147477733 has natively added scene component(s), but none of them were set as the actor's RootComponent - picking one arbitrarily
[2022.11.21-10.02.58:397][849]LogIcarusGameModeSurvival: -------- Server now has players ---------
[2022.11.21-10.02.58:397][849]LogNet: Join succeeded: Katala Swiftwind
[2022.11.21-10.02.58:409][850]LogIcarusGameStateRecording: Display: RecordToProspectSaveState - NumRecorders: 526
[2022.11.21-10.02.58:440][850]LogIcarusGameStateRecording: Display: RecordToProspectSaveState complete
[2022.11.21-10.02.58:440][850]LogIcarusGameModeSurvival: Verbose: RequestUpdateProspectState
[2022.11.21-10.02.58:475][850]LogIcarusGameModeSurvival: OnUpdateProspectSuccess
03:02:59
[2022.11.21-10.02.59:381][877]LogWeatherController: Display: Katala Swiftwind just entered new biome: Arctic
03:03:02
[2022.11.21-10.03.02:620][975]LogConnectedPlayers: Display: AddConnectedPlayer - UserId: 76561198051191700 | PlayerName: Katala Swiftwind
[2022.11.21-10.03.02:620][975]LogConnectedPlayers: Verbose: OnRep_ConnectedPlayers
[2022.11.21-10.03.02:620][975]LogConnectedPlayers: Verbose: OnRep_ConnectedPlayers ConnectedPlayer at index [0] - PlayerID: 76561198051191700_-1 | Initialised: false
```

**Comment by Greelan** [comment] 2022-11-21 10:09
It should take you right through to create the prospect if "Create and launch prospect" is selected, AND if the save name does not already exist.

**Comment by gkuba** [comment] 2022-11-21 10:10
it did. It also takes you right to the lobby after a restart for you to load or create a new one. I'm still playing around with it.

**Comment by Greelan** [comment] 2022-11-21 10:14
Gotcha. There is a timeout (default 5 mins) that takes it back to the lobby if no-one connects in that time. Can be set to -1 for the prospect to run indefinitely (paused until someone joins), but if the server is shutdown in AMP without having returned to the lobby, data loss/corruption will occur - either the prospect save will be unusable, or it won't have the last save

**Comment by Greelan** [comment] 2022-11-21 10:14
Coz OS_CLOSE doesn't cause a clean shutdown (and other methods like CtrlC don't work)

**Comment by gkuba** [comment] 2022-11-21 10:15
So far even with the restart it reloaded just fine with no corruption from what I can tell. So "hopefully" that won't actually be an issue.

**Comment by Greelan** [comment] 2022-11-21 10:17
Try this, launch a new prospect, then shutdown the server in AMP before the return to lobby timeout. On next start, with Load prospect or Resume prospect selected, the prospect won't load (will stay in the lobby). You can see in the json file for the prospect that the ProspectBlob section is unpopulated

**Comment by gkuba** [comment] 2022-11-21 10:19
Clicking resume doesn't work correct but clicking Join and going back to the server it gives you the option to load the save and that works fine.

**Comment by Greelan** [comment] 2022-11-21 10:20
You mean in the lobby UI? I am talking about through AMP's UI

**Comment by gkuba** [comment] 2022-11-21 10:20
When you load / create a new prospect you do get a "network error" and kicked out but you just reconnect and everything is fine. It seems like it doesn't transition from lobby to in prospect very well yet.

**Comment by gkuba** [comment] 2022-11-21 10:24
Changing it in AMP UI to load works also but honestly its probably best to just have them use the in game server load option as that way there is no confusion. From what I can tell that is the intended way to do it.

**Comment by Greelan** [comment] 2022-11-21 10:25
Not sure about whether intended, given that they give 3 additional ways to do it with the dedicated server - command line, ini file, and RCON (console). But eventually they may streamline this

**Comment by gkuba** [comment] 2022-11-21 10:27
I can see the need to load via one of those ways if you set an auto-restart and make it never go to the lobby. 
Otherwise you have to reload from the lobby UI anyways.

**Comment by gkuba** [comment] 2022-11-21 10:28
![image](https://user-images.githubusercontent.com/1753639/203027512-d83be576-0c12-4ed0-accf-234ec694ec07.png)
![image](https://user-images.githubusercontent.com/1753639/203027557-712a15bf-e451-4559-844f-becbdbdfa718.png)

**Comment by gkuba** [comment] 2022-11-21 10:47
Everything I've tested seems to work. I haven't found any issues. I'll poke around more later I'm going to get a few hours of sleep. Let me know if you need me to test something specific.

**Comment by Greelan** [comment] 2022-11-21 11:04
Nice. AMP log lines for user join, leave and chat (if  they exist) so I can complete the regex, please

**Comment by gkuba** [comment] 2022-11-21 11:08
Log lines above for join / exit. I'll get chat real quick if it shows up.

**Comment by gkuba** [comment] 2022-11-21 11:12
Chat does not show in console

**Comment by Greelan** [comment] 2022-11-21 11:14
Ah, soz, didn't realise that was why you posted those logs

**Comment by gkuba** [comment] 2022-11-21 11:15
its np

**Comment by Greelan** [comment] 2022-11-21 11:22
For log in, I was thinking about one of these, as they reflect an actual join rather than just a request:

`[2022.11.21-10.02.58:397][849]LogNet: Join succeeded: Katala Swiftwind`

or

`[2022.11.21-10.03.02:620][975]LogConnectedPlayers: Display: AddConnectedPlayer - UserId: 76561198051191700 | PlayerName: Katala Swiftwind`

The second one has better info, but is that when they actually join a prospect, rather than just enter the lobby? I'd think it would be better to reflect when they joined the lobby.

**Comment by Greelan** [comment] 2022-11-21 11:24
Trouble with the first line though is that it only includes the name, not SteamID, and the user leave lines only have SteamID - so they wouldn't match

**Comment by gkuba** [comment] 2022-11-21 22:06
Ah true I'd go with the second one also

**Comment by Greelan** [comment] 2022-11-22 01:26
Does the second message appear when someone connects to the lobby, or only when they enter a prospect?

**Comment by gkuba** [comment] 2022-11-22 04:08
Um I'll have to give that a check.

**Comment by gkuba** [comment] 2022-11-22 05:52
Here is what is in the console when you join the lobby. 

```
[2022.11.22-05.50.14:042][143]LogOnline: STEAM: Adding P2P connection information with user 76561198051191700 (Name: UNKNOWN [0x1100001056B6B94])
22:50:17
[2022.11.22-05.50.17:602][250]LogNet: NotifyAcceptingConnection accepted from: 76561198051191700:19132
[2022.11.22-05.50.17:602][250]LogNet: NotifyAcceptingConnection accepted from: 76561198051191700:19132
[2022.11.22-05.50.17:603][250]LogNet: NotifyAcceptingConnection accepted from: 76561198051191700:19132
[2022.11.22-05.50.17:603][250]LogNet: NotifyAcceptingConnection accepted from: 76561198051191700:19132
[2022.11.22-05.50.17:635][251]LogNet: NotifyAcceptingConnection accepted from: 76561198051191700:19132
[2022.11.22-05.50.17:635][251]LogNet: Server accepting post-challenge connection from: 76561198051191700:19132
[2022.11.22-05.50.17:636][251]PacketHandlerLog: Loaded PacketHandler component: OnlineSubsystemSteam.SteamAuthComponentModuleInterface ()
[2022.11.22-05.50.17:636][251]PacketHandlerLog: Loaded PacketHandler component: Engine.EngineHandlerComponentFactory (StatelessConnectHandlerComponent)
[2022.11.22-05.50.17:636][251]LogOnline: STEAM: Adding user 76561198051191700:19132 from RegisterConnection
[2022.11.22-05.50.17:637][251]LogNet: NotifyAcceptedConnection: Name: DedicatedServerEntry, TimeStamp: 11/21/22 21:50:17, [UNetConnection] RemoteAddr: 76561198051191700:19132, Name: SteamNetConnection_2147482212, Driver: GameNetDriver SteamNetDriver_2147482226, IsServer: YES, PC: NULL, Owner: NULL, UniqueId: INVALID
[2022.11.22-05.50.17:637][251]LogNet: AddClientConnection: Added client connection: [UNetConnection] RemoteAddr: 76561198051191700:19132, Name: SteamNetConnection_2147482212, Driver: GameNetDriver SteamNetDriver_2147482226, IsServer: YES, PC: NULL, Owner: NULL, UniqueId: INVALID
[2022.11.22-05.50.17:639][251]LogOnline: STEAM: AUTH HANDLER: Sending auth result to user 76561198051191700 with flag success? 1
[2022.11.22-05.50.17:669][252]LogNet: NotifyAcceptingChannel Control 0 server World /Game/Maps/DedicatedServerEntry.DedicatedServerEntry: Accepted
[2022.11.22-05.50.17:669][252]LogNet: Remote platform little endian=1
[2022.11.22-05.50.17:669][252]LogNet: This platform little endian=1
[2022.11.22-05.50.17:669][252]LogNetVersion: Icarus 1.2.26.104311-rel-Styx, NetCL: 0, EngineNetVer: 17, GameNetVer: 0 (Checksum: 41960097)
[2022.11.22-05.50.17:702][253]LogNet: Login request: ?password=1234?Name=Katala Swiftwind userId: Steam:UNKNOWN [0x1100001056B6B94] platform: Steam
[2022.11.22-05.50.17:734][254]LogNet: Client netspeed is 640000
22:50:18
[2022.11.22-05.50.18:430][275]LogNet: Join request: /Game/Maps/DedicatedServerEntry?password=1234?Name=Katala Swiftwind?SplitscreenCount=1
[2022.11.22-05.50.18:431][275]LogGameMode: FindPlayerStart: PATHS NOT DEFINED or NO PLAYERSTART with positive rating
[2022.11.22-05.50.18:435][275]LogGameMode: Display: Match State Changed from WaitingToStart to InProgress
[2022.11.22-05.50.18:438][275]LogGameState: Match State Changed from WaitingToStart to InProgress
[2022.11.22-05.50.18:439][275]LogNet: Join succeeded: Katala Swiftwind
[2022.11.22-05.50.18:662][282]LogConnectedPlayers: Display: AddConnectedPlayer - UserId: 76561198051191700 | PlayerName: Katala Swiftwind
```
This last line is what I would use.

**Comment by Greelan** [comment] 2022-11-22 07:22
I agree. Now updated.

**Comment by gkuba** [comment] 2022-11-22 07:32
K I'll grab and test it on a new server shortly

**Comment by gkuba** [comment] 2022-11-22 11:09
Everything seems to work on my end.

**Comment by Greelan** [comment] 2022-11-22 11:27
Cool. Thanks for testing. No doubt the devs will break it all, but anyways...

**Comment by Greelan** [comment] 2022-11-22 11:41
https://github.com/CubeCoders/AMPTemplates/pull/237

**Comment by Greelan** [comment] 2022-11-28 04:50
Now merged

**Closed by Greelan** 2022-11-28 04:50 UTC
